[package]
name = "wasm-dev-bool-hello-world"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.57"
js-sys = "0.3.57"
reqwest = "0.11.10"
wasm-bindgen = "0.2.80"
wasm-bindgen-futures = "0.4.30"
